server:
      port: 8080
      servlet:
           context-path: /ruigoubusiness
           
logging:
  level:
    org.springframework: debug
    com.neusoft.ruigoubusiness.mapper: debug
   
     
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruigou?characterEncoding=utf-8
    username: root
    password: 1219

mybatis:
   type-aliases-package: com.neusoft.ruigoubusiness.po  
   
    